version: 'build #{build}'

before_build:
  - git submodule update --init

build_script:
  - gradlew -PpublishMode build

after_build:
  - if %APPVEYOR_REPO_TAG%==true ( gradlew -PpublishMode -PVERSION_SUFFIX bintrayUpload )
    else ( gradlew -PpublishMode publishToMavenLocal )
  - copy libui\build\classes\kotlin\windows\main\libui-cinterop-libui.klib libui-windows.klib
  - copy libui\build\classes\kotlin\windows\main\libui.klib libui-ktx-windows.klib
  - 7z a libui-samples-windows.zip
         .\samples\controlgallery\build\bin\windows\main\release\executable\controlgallery.exe
         .\samples\datetime\build\bin\windows\main\release\executable\datetime.exe
         .\samples\drawtext\build\bin\windows\main\release\executable\drawtext.exe
         .\samples\form\build\bin\windows\main\release\executable\form.exe
         .\samples\hello\build\bin\windows\main\release\executable\hello.exe
         .\samples\hello-ktx\build\bin\windows\main\release\executable\hello-ktx.exe
         .\samples\histogram\build\bin\windows\main\release\executable\histogram.exe
         .\samples\logo\build\bin\windows\main\release\executable\logo.exe
         .\samples\table\build\bin\windows\main\release\executable\table.exe
         .\samples\timer\build\bin\windows\main\release\executable\timer.exe
  - 7z l libui-samples-windows.zip

artifacts:
  - path: libui-windows.klib
    name: interop
  - path: libui-ktx-windows.klib
    name: library
  - path: libui-samples-windows.zip
    name: samples

deploy:
  provider: GitHub
  artifact: interop, library, samples
  auth_token:
    secure: "2l/602m6FkqAB9TTIAkPX3Erfwg9jVTlf/Inmf2dWcbOrJJzK/WrCUIgY3B4ngly"
  on:
    appveyor_repo_tag: true

environment:
  BINTRAY_API_KEY:
    secure: BhHNDSz5XPW90PhX7c/e+t4A3nNPNtsauux+yE9Lzjf90YR4PDMdk1bKiTS7nW5X
